// Supabase → 정적 사이트 데이터 동기화.
//
// Supabase breach_findings / scan_runs 를 읽어 lib/data/generated/breachMonitor.ts 를 갱신한다.
// GitHub Actions 빌드 단계(자정 스캔 이후)에서 실행되어 대시보드에 실데이터를 반영한다.
// Supabase 미설정 시 조용히 종료(커밋된 스냅샷/로컬 스캔 결과를 그대로 사용).

import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const root = process.cwd();
const generatedFile = join(root, "lib", "data", "generated", "breachMonitor.ts");

const URL = process.env.SUPABASE_URL?.trim() || process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
const KEY =
  process.env.SUPABASE_ANON_KEY?.trim() ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() ||
  process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();

if (!URL || !KEY) {
  console.log("[pull] SUPABASE_URL/KEY 미설정 → 스킵(기존 생성 파일 유지)");
  process.exit(0);
}

const headers = { apikey: KEY, Authorization: `Bearer ${KEY}` };

async function rest(path) {
  const res = await fetch(`${URL}/rest/v1/${path}`, { headers });
  if (!res.ok) throw new Error(`Supabase ${path} → HTTP ${res.status} ${(await res.text()).slice(0, 200)}`);
  return res.json();
}

const SEVERITY_RANK = { low: 0, medium: 1, high: 2, critical: 3 };

async function main() {
  // 유출 항목 (severity desc, breach_date desc)
  const rows = await rest(
    "breach_findings?select=finding_id,account_masked,domain,breach_name,breach_title,breach_date,data_classes,severity,is_new,discovered_at,source&order=severity.desc,breach_date.desc"
  );
  // 스캔 이력 (최근 30건)
  const runs = await rest(
    "scan_runs?select=scanned_at,total,new_count,source,status,is_demo,domains,sources,note&order=scanned_at.desc&limit=30"
  );
  // 인포스틸러(도메인 전수)
  const infRows = await rest(
    "infostealer_findings?select=domain,source,total,employees,users,third_parties,affected_urls,scanned_at&order=total.desc"
  );

  const findings = rows.map((r) => ({
    id: r.finding_id,
    accountMasked: r.account_masked,
    domain: r.domain,
    breachName: r.breach_name,
    breachTitle: r.breach_title ?? r.breach_name,
    breachDate: r.breach_date ?? "",
    dataClasses: r.data_classes ?? [],
    severity: r.severity,
    isNew: !!r.is_new,
    discoveredAt: r.discovered_at,
    source: r.source ?? "",
  }));
  findings.sort((a, b) => {
    if (a.isNew !== b.isNew) return a.isNew ? -1 : 1;
    if (SEVERITY_RANK[b.severity] !== SEVERITY_RANK[a.severity])
      return SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity];
    return (b.breachDate || "").localeCompare(a.breachDate || "");
  });

  const bySeverity = { critical: 0, high: 0, medium: 0, low: 0 };
  const byDomainMap = new Map();
  let newCount = 0;
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
    byDomainMap.set(f.domain, (byDomainMap.get(f.domain) ?? 0) + 1);
    if (f.isNew) newCount++;
  }

  const latestRun = runs[0];
  // 설정된 모니터링 도메인(스캔 기록) 우선, 없으면 발견된 도메인.
  const domains = latestRun?.domains?.length ? latestRun.domains : [...byDomainMap.keys()];
  const history = [...runs]
    .reverse()
    .map((r) => ({ scannedAt: r.scanned_at, total: r.total, newCount: r.new_count }));

  const scan = {
    generatedAt: latestRun?.scanned_at ?? new Date().toISOString(),
    source: latestRun?.source ?? "Supabase",
    status: latestRun?.status ?? "ok",
    isDemo: false,
    domains,
    findings,
    summary: {
      total: findings.length,
      newCount,
      bySeverity,
      byDomain: [...byDomainMap.entries()].map(([domain, count]) => ({ domain, count })),
    },
    history,
    note: latestRun?.note ?? undefined,
    infostealer: infRows.map((i) => ({
      domain: i.domain,
      source: i.source,
      total: i.total,
      employees: i.employees,
      users: i.users,
      thirdParties: i.third_parties,
      affectedUrls: i.affected_urls ?? [],
      scannedAt: i.scanned_at,
    })),
    sources: latestRun?.sources ?? [],
  };

  await mkdir(join(root, "lib", "data", "generated"), { recursive: true });
  const banner = "// Auto-generated by scripts/pull_from_supabase.mjs. Do not edit by hand.\n";
  await writeFile(
    generatedFile,
    banner +
      'import type { BreachScan } from "@/lib/types/breachMonitor";\n\n' +
      "export const breachScan: BreachScan = " +
      JSON.stringify(scan, null, 2) +
      ";\n",
    "utf8"
  );
  console.log(`[pull] Supabase → 생성 파일 갱신: 총 ${findings.length}건 (신규 ${newCount})`);
}

main().catch((err) => {
  console.error(`[pull] 실패: ${err.message}`);
  process.exitCode = 1;
});
